baseurl: ''
key: osg # Use this for shared content
theme: jekyll-theme-minimal
title: OSG
description: A national, distributed computing partnership for data-intensive research
google_analytics: UA-69012-28

# Jekyll does not build hidden directories by default.
include:
  - .well-known
  - .nojekyll


exclude:
  - _spotlights/images

defaults:
  - scope:
      path: ""
    values:
      layout: container
  - scope:
      path: "_about"
      type: about
    values:
      layout: about
  - scope:
      path: "_news"
      type: news
    values:
      layout: posts
  - scope:
      path: "_spotlights"
      type: spotlights
    values:
      layout: posts
  - scope:
      path: "_events"
    values:
      layout: events

collections:
  about:
    permalink: /:collection/:path/
    output: true
  events:
    permalink: /events/:path/
    output: true
  news:
    permalink: /news/:year/:month/:day/:title.html
    output: true
  spotlights:
    permalink: /spotlights/:title.html
    output: true

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
